### ISSUE TITLE
actions on module require

### ISSUE THREAD

**Issue by keis** [codetunnel/hearthstone-log-watcher#1]
The module does a bunch of stuff when loaded most notably writing the config file. This makes it hard to test and to pass any options to the code. It would be really handy to specify a configpath/logpath for when you're not running in the default installation path or like me running hearthstone through wine on linux.

A better way to use might look something like this

```
var LogWatcher = require('hearthstone-log-watcher');
var logWatcher = new LogWatcher({
  configPath: "/whatever/here"
});
logWatcher.on(...);
logWatcher.start();
```

WDYT? I'll try to get a PR ready if you think this sounds good.

**Comment by AlexAllocated** [comment]
Absolutely. I think that's a great idea, and a definite oversight on my part. I would just leave the current logic as the default while allowing the config option to override. You're welcome to submit a PR, or I'm also happy to just implement said behavior for you this evening after I get off work :)
