### ISSUE TITLE
partial log lines are discarded

### ISSUE THREAD

**Issue by keis** [codetunnel/hearthstone-log-watcher#3]
any log lines that are not complete when the file is being read will be discarded because the next read will start in the middle of that line. This happens a lot for me on wine (In fact I never seem to see a complete line) but could in theory happen on any platform.

adding a console.log after each buffer read I get output like this, where each `CHUNK` is a separate read

```
CHUNK  ZoneChangeList.Pr
CHUNK ocessChanges() - 
CHUNK START waiting for
CHUNK  [name=Knife Jug
CHUNK gler id=22 zon
CHUNK e=HAND zoneP
CHUNK os=0 cardId=NEW1_
CHUNK 019 player=1] 
CHUNK to load (z
CHUNK oneChange
CHUNK d=True co
CHUNK ntrollerC
CHUNK hanged=Fa
CHUNK lse power
CHUNK Task=(not
CHUNK  null))
```

The module will have to keep a internal buffer where it keeps any lines not completed yet. You could perhaps also take a look at using `https://www.npmjs.com/package/tail` which promises to solve the gritty details of watching a file for new lines. I never used that module however so I can't really vouch for the quality of it.

**Comment by AlexAllocated** [comment]
I'm not able to duplicate this behavior on OS X. Node's `fs.watch` simply notifies whenever the file has been modified. I do the file reading myself. This definitely does not happen on OSX, but I think I know why it's happening for you. [This line](https://github.com/codetunnel/hearthstone-log-watcher/blob/master/index.js#L73) splits the buffer up by newline characters and loops through the lines. On Windows a carriage return is a newline character followed by a line feed character (`\r\n` instead of just `\n`) and Hearthstone running on Wine is almost certainly writing out Windows newline characters to the file and could be screwing up the buffer splitting.

The `fs.watch` function only fires when the log file has been modified, and the file only gets modified when Hearthstone appends an entire line to it. Hearthstone doesn't write partial lines to the file (i.e. the file watching function doesn't fire until a whole line is written out to the file) so it's definitely our code. We're already checking for OS when determining default file paths for the log and config files, so I'll just save that check and use it to determine the newline pattern I should use.

**Comment by chevex** [comment]
Actually it looks like we can use the node core `os` module to access `os.EOL` (end of line) which has the platform-specific end of line character :)

**Comment by AlexAllocated** [comment]
https://github.com/codetunnel/hearthstone-log-watcher/commit/107c47b7eb588d50cdad935f1a51a080ad1c9a4b

That commit hopefully fixes the issue. Try it out and tell me if you still see the same problem. It's published to NPM as v1.1.2. I would test on Windows more but I only have one valid key and it's used on my home desktop. I have a VMware machine on my Macbook but Windows is unlicensed on it and Blizzard detects this and prevents installation of their software.

**Comment by keis** [comment]
yeah. it's definitely caused by some weird interaction with wine or possibly the watch implementation on linux.

I added the log just above that line and it seems like buffer from readSync simply does not end in a EOL. Possibly the file is not being line buffered when running through wine.

```
    console.log("CHUNK", buffer.toString());

    // Iterate over each line in the buffer.
    buffer.toString().split('\n').forEach(function (line) {
```

the eol bit is also a issue but is quite easy to hack around for now, os.EOL wont really help because the proper eol for linux is the simple `\n` but wine uses `\r\n` like windows.

**Comment by AlexAllocated** [comment]
But if on linux you're running Hearthstone via Wine, won't it still write Windows line endings to the file?

**Comment by keis** [comment]
indeed wine will write windows style line endings. but `os.EOL` will be the linux line ending because I'm running node outside of wine.

**Comment by AlexAllocated** [comment]
Ah yes, duh. It's too early in the morning over here :P

**Comment by AlexAllocated** [comment]
I'll investigate some more. Let me add the log call in the same place and see what my buffers look like. Considering that the app has been 100% accurate in tracking my deck so far, I'm inclined to believe you're right about it being some Wine weirdness.

**Comment by AlexAllocated** [comment]
![image](https://cloud.githubusercontent.com/assets/874394/6713830/7a04a910-cd5a-11e4-84ba-b8d6d2685c47.png)

This is what the output looks like when I add `console.log('CHUNK', buffer.toString());` right above the line where I split up and iterate the buffer. Each buffer read is supposed to be all content since the last read. It looks like that is working properly on my Mac.

**Comment by keis** [comment]
yeah that looks much saner, you even get multiple log lines with each read

**Comment by keis** [comment]
Ah, but sometimes you get the opening [ of [Zone] as the last bit of a buffer so something a bit odd is going even here. even though it doesn't mess things up.

like the line at the top where you draw dr. boom

**Comment by AlexAllocated** [comment]
I just fixed that exact issue.

**Comment by keis** [comment]
hmm. so this seems very wine specific. I might poke around with a bit later and see if I can figure something out

**Comment by AlexAllocated** [comment]
![image](https://cloud.githubusercontent.com/assets/874394/6714112/36619900-cd5c-11e4-8260-d513b2abfb87.png)

Here's the new output after fixing that small bug. I guess the line it affected was never matched by an expression anyway, so it never really affected the watcher, but at least it's working properly now.

**Comment by AlexAllocated** [comment]
It probably does have to do with how often the watch function runs. I'm betting you're right and something is wonky with Wine and the way node monitors file changes.

**Comment by DooBLER** [comment]
Hi
I write HS log reader in python.
This is mine function for reading log updates, I think it can help.
It handles "\r" at the end and incomplete lines.
Python is easy readable and i comented source for you.
Sorry for my english.

``` python
    def log_changed(self, file_p):
        """Executed when log file changes

        :param file_p: log file path from file watcher
        :return:
        """

        # do not read every log file change
        # 1/5 is fast enough
        self.log_change_delay += 1
        if self.log_change_delay > 5:
            self.log_change_delay = 0

            while True:
                # get NEW file content
                new_text = self.log_file.read().decode('utf8')
                nt_len = len(new_text)

                if nt_len > 0:

                    # split lines
                    new_lines = new_text.split(u"\n")

                    # loop over all lines except last
                    # if there is only one line then loop will not run
                    for new_line in new_lines[:-1]:

                        # only not empty lines
                        if len(new_line) > 0:
                            # if there is previous incomplete line
                            if len(self.incomplete_line) > 0:
                                # add this line to incomplete line
                                new_line = u"%s%s" % (self.incomplete_line,
                                                      new_line)
                                # empty "incomplete bufor" because
                                # if program is here
                                # this line had "\n" at the end
                                self.incomplete_line = u""

                            # only lines starting with "["
                            # this cuts log size for further processing by ~ 1/2
                            if new_line[0] == u"[":
                                # emit signal with one complete line
                                # also remove "\r" etc.
                                self.dataReady.emit(new_line.rstrip())

                    # if last line not empty and not "\n" at the end
                    if len(new_lines[-1]) > 0:
                        # add line to incomplete line
                        self.incomplete_line = u"%s%s" % (
                            self.incomplete_line, new_lines[-1])
                else:
                    return
```

**Comment by AlexAllocated** [comment]
Thanks for the help @DooBLER. I apologize for not closing this earlier, but this isn't an issue on any platform except Wine under linux. The watcher works as expected on OS X and Windows. I'm not intending to officially support Wine but anyone who wants to maintain a modified fork for users running Hearthstone on Wine are welcome to :)
