### ISSUE TITLE
Game Over condition in Adventure mode

### ISSUE THREAD

**Issue by DooBLER** [codetunnel/hearthstone-log-watcher#8]
When you play against bosses in adventure mode, oponent "Entity" value in newPlayerRegex is different than in gameOverRegex

The relevant parts of the log:

newPlayerRegex:

```
[Power] GameState.DebugPrintPower() - TAG_CHANGE Entity=The Innkeeper tag=TEAM_ID value=2
...
[Power] GameState.DebugPrintPower() - TAG_CHANGE Entity=DooB tag=TEAM_ID value=1
```

mulligan:

```
[Power] GameState.DebugPrintChoice() - id=1 ChoiceType=MULLIGAN Cancelable=False CountMin=0 CountMax=3
```

gameOverRegex:

```
[Power] GameState.DebugPrintPower() - TAG_CHANGE Entity=DooB tag=PLAYSTATE value=LOST
[Power] GameState.DebugPrintPower() - TAG_CHANGE Entity=Instructor Razuvious tag=PLAYSTATE value=WON
```

I tested it only on Naxxramas.

**Comment by AlexAllocated** [comment]
Thanks for bringing this up. Should be a trivial fix :). I'll check it out sometime this weekend.

**Comment by AlexAllocated** [comment]
I'm actually not sure there's anything that can be done about this. It seems the problem is with the log, not the tracker. I'm going to double-check, but if the log reports "The Innkeeper" in the beginning then that's what it reports. I'll check to make sure there isn't some other way for me to find the adventure mode boss name but it looks like Blizzard's log is just inaccurate.

**Comment by DooBLER** [comment]
I don't implemented this yet in my tracker, but i plan to use zone change event.
pseudocode:

```
if "before mulligan" and zone change == "to oponent (hero)" then player['hero'] = "card name"
```

then in gameOverEvent:

```
    for player in playersarray {
         if player['name'] == "Entity from regexp" OR player['hero'] == "Entity from regexp" {
         ...
        }
    }
```

When i implement this i can paste code here.

Also I don't have any idea what happens when you or oponent  play Lord Jaraxxus (i dont have this card yet).
